kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # Existing API server port (keep this!)
  extraPortMappings:
  - containerPort: 6443  # Kubernetes API
    hostPort: 6443
    protocol: TCP
  # Add these new ports for ingress
  - containerPort: 80     # HTTP
    hostPort: 80
    protocol: TCP
  - containerPort: 443    # HTTPS
    hostPort: 443
    protocol: TCP
- role: worker
  image: kindest/node:v1.22.0